Repository AY2223S2-CS2113-F10-4/tp, pull requests merged in 2023-03, with the labels that each got.

#24 11 test search feat
  src/main/java/seedu/dukeofbooks/data/book/BorrowableItem.java
  src/main/java/seedu/dukeofbooks/data/book/Topic.java
  src/main/java/seedu/dukeofbooks/data/inventory/Inventory.java
  src/main/java/seedu/dukeofbooks/data/loan/LoanRecords.java
  src/test/java/seedu/controller/SearchControllerTest.java
Labels: type.enhancement

#25 feat: add callable commands
  src/main/java/seedu/dukeofbooks/command/BorrowCommand.java
  src/main/java/seedu/dukeofbooks/command/CommandResult.java
  src/main/java/seedu/dukeofbooks/command/HistoryCommand.java
  src/main/java/seedu/dukeofbooks/command/InventoryCommand.java
  src/main/java/seedu/dukeofbooks/command/RenewCommand.java
  src/main/java/seedu/dukeofbooks/command/ReturnCommand.java
  src/main/java/seedu/dukeofbooks/command/SearchCommand.java
  src/main/java/seedu/dukeofbooks/data/loan/LoanRecords.java
  src/main/java/seedu/dukeofbooks/data/person/Person.java
Labels: priority.high

#32 29 feat borrow renew return
  src/main/java/seedu/dukeofbooks/command/BorrowCommand.java
  src/main/java/seedu/dukeofbooks/command/LoanCommand.java
  src/main/java/seedu/dukeofbooks/command/RenewCommand.java
  src/main/java/seedu/dukeofbooks/command/ReturnCommand.java
  src/main/java/seedu/dukeofbooks/controller/LoanController.java
  src/main/java/seedu/dukeofbooks/data/loan/LoanRecords.java
  src/test/java/seedu/command/BorrowCommandTest.java
  src/test/java/seedu/command/RenewCommandTest.java
  src/test/java/seedu/command/ReturnCommandTest.java
  src/test/java/seedu/controller/LoanControllerTest.java
Labels: type.enhancement, type.epic, priority.high

#33 feat: search and inventory command
  src/main/java/seedu/dukeofbooks/command/Command.java
  src/main/java/seedu/dukeofbooks/command/InventoryCommand.java
  src/main/java/seedu/dukeofbooks/command/SearchCommand.java
  src/main/java/seedu/dukeofbooks/common/Messages.java
  src/main/java/seedu/dukeofbooks/controller/InventoryController.java
Labels: priority.high

#34 add history command
  src/main/java/seedu/dukeofbooks/command/HistoryCommand.java
  src/main/java/seedu/dukeofbooks/data/book/BorrowHistory.java
  src/main/java/seedu/dukeofbooks/data/person/Person.java
  src/test/java/seedu/data/book/BorrowHistoryTest.java
Labels: type.enhancement

#40 search and librarian command
  README.md
  src/main/java/seedu/dukeofbooks/DukeOfBooks.java
  src/main/java/seedu/dukeofbooks/command/InventoryCommand.java
  src/main/java/seedu/dukeofbooks/command/SearchCommand.java
  src/main/java/seedu/dukeofbooks/common/Messages.java
  src/main/java/seedu/dukeofbooks/controller/InventoryController.java
  src/main/java/seedu/dukeofbooks/controller/SearchController.java
  src/main/java/seedu/dukeofbooks/data/book/Book.java
  src/main/java/seedu/dukeofbooks/data/book/BorrowHistory.java
  src/main/java/seedu/dukeofbooks/data/book/Isbn.java
  src/main/java/seedu/dukeofbooks/parser/Parser.java
  src/test/java/seedu/command/SearchCommandTest.java
  src/test/java/seedu/controller/InventoryControllerTest.java
  src/test/java/seedu/controller/SearchControllerTest.java
  src/test/java/seedu/data/book/BorrowHistoryTest.java
Labels: type.enhancement

#45 doc: search and add
  docs/DeveloperGuide.md
  docs/rename.puml
Labels: documentation

#49 46 feat dg with v10 functionalities
  build.gradle
  docs/DeveloperGuide.md
  docs/search.puml
  src/main/java/seedu/dukeofbooks/command/SearchCommand.java
Labels: documentation

#43 Enable assertion
  build.gradle
Labels: type.chore

#52 docs: search and librarian docs
  docs/UserGuide.md
Labels: documentation

#63 59 feat search command to work with title and topic
  src/main/java/seedu/dukeofbooks/DukeOfBooks.java
  src/main/java/seedu/dukeofbooks/command/SearchCommand.java
  src/main/java/seedu/dukeofbooks/common/Messages.java
  src/main/java/seedu/dukeofbooks/controller/SearchController.java
  src/main/java/seedu/dukeofbooks/data/book/Book.java
  src/main/java/seedu/dukeofbooks/data/book/Isbn.java
  src/main/java/seedu/dukeofbooks/data/person/Person.java
  src/main/java/seedu/dukeofbooks/data/person/Phone.java
  src/main/java/seedu/dukeofbooks/parser/UserCommandParser.java
  src/test/java/seedu/command/SearchCommandTest.java
  src/test/java/seedu/controller/SearchControllerTest.java
Labels: type.enhancement
