Repository AY2223S2-CS2113-F10-4/tp, pull requests merged in 2023-04, with the labels that each got.

#116 book database & search bug
  database/books.txt
  src/main/java/seedu/dukeofbooks/DukeOfBooks.java
  src/main/java/seedu/dukeofbooks/ReadWriteData.java
  src/main/java/seedu/dukeofbooks/controller/SearchController.java
  src/main/java/seedu/dukeofbooks/data/inventory/Inventory.java
Labels: type.enhancement, priority.high

#125 feat: check item availability
  docs/team/yongjian.md
  src/main/java/seedu/dukeofbooks/DukeOfBooks.java
  src/main/java/seedu/dukeofbooks/command/CheckItemAvailabilityCommand.java
  src/main/java/seedu/dukeofbooks/command/ReturnCommand.java
  src/main/java/seedu/dukeofbooks/command/UserCommand.java
  src/main/java/seedu/dukeofbooks/controller/LoanController.java
  src/main/java/seedu/dukeofbooks/controller/PaymentController.java
  src/main/java/seedu/dukeofbooks/data/exception/PaymentUnsuccessfulException.java
  src/main/java/seedu/dukeofbooks/data/loan/Loan.java
  src/main/java/seedu/dukeofbooks/parser/UserCommandParser.java
  src/test/java/seedu/command/RenewCommandTest.java
  src/test/java/seedu/command/ReturnCommandTest.java
  text-ui-test/EXPECTED.TXT
  tp.jar
Labels: type.enhancement, priority.medium

#128 fixed librarian add command
  docs/UserGuide.md
  src/main/java/seedu/dukeofbooks/command/InventoryCommand.java
  src/main/java/seedu/dukeofbooks/parser/UserCommandParser.java
Labels: type.bug

#61 Add Access Management User Guide
  docs/UserGuide.md
Labels: documentation

#130 add list command implementation
  database/users.txt
  src/main/java/seedu/dukeofbooks/ReadWriteData.java
  src/main/java/seedu/dukeofbooks/command/ListCommand.java
  src/main/java/seedu/dukeofbooks/controller/ListController.java
Labels: priority.high

#134 133 doc update all documentations
  README.md
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/README.md
  docs/UserGuide.md
  docs/images/dx.png
  docs/images/rayden.png
  docs/images/tk.png
  docs/images/yj.png
Labels: documentation, priority.high

#140 Update DG for AccessCommands
  docs/DeveloperGuide.md
Labels: documentation

#136 fix bug for check borrowing status
  src/main/java/seedu/dukeofbooks/command/ListCommand.java
  src/main/java/seedu/dukeofbooks/controller/LoanController.java
Labels: type.bug, priority.high, severity.high

#137 129 bug access management
  database/users.txt
  src/main/java/seedu/dukeofbooks/ReadWriteData.java
Labels: type.bug, severity.medium

#139 Add Due Date to Borrow History
  src/main/java/seedu/dukeofbooks/data/book/BorrowHistory.java
Labels: type.enhancement

#144 143 doc yongjian ppp
  docs/team/ngyongjian.md
  docs/team/yongjian.md
Labels: documentation, priority.high

#150 Add Danxu PPP
  docs/team/DanxuZhang.md
  docs/team/danxuzhang.md
Labels: documentation

#145 Update ppp link in AboutUs.md
  docs/AboutUs.md
Labels: documentation, type.chore

#147 Add "" to img src to allow display in web format
  docs/AboutUs.md
Labels: type.bug, documentation, severity.medium

#156 edit documentations
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/raydent30.md
Labels: documentation, priority.medium

#162 doc: update search note
  docs/DeveloperGuide.md
Labels: type.bug, documentation

#161 feat: FAQ common questions
  docs/UserGuide.md
Labels: documentation

#157 TzeKean ppp
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/team/HiIAmTzeKean.md
  docs/team/tzekean.md
Labels: documentation

#165 Aboutus table
  docs/AboutUs.md
  docs/DeveloperGuide.md
  src/main/java/seedu/dukeofbooks/DukeOfBooks.java
  src/main/java/seedu/dukeofbooks/command/BorrowCommand.java
  src/main/java/seedu/dukeofbooks/command/CheckBorrowingStatusCommand.java
  src/main/java/seedu/dukeofbooks/command/RenewCommand.java
  src/main/java/seedu/dukeofbooks/command/ReturnCommand.java
  src/main/java/seedu/dukeofbooks/common/Messages.java
  src/main/java/seedu/dukeofbooks/controller/PaymentController.java
  src/main/java/seedu/dukeofbooks/parser/UserCommandParser.java
  src/main/java/seedu/dukeofbooks/ui/TextUi.java
Labels: documentation

#167 bug: display block style on image
  docs/AboutUs.md
Labels: documentation

#172 feat: image renders!
  docs/AboutUs.md
Labels: documentation

#158 test: inventory controller
  src/main/java/seedu/dukeofbooks/command/InventoryCommand.java
  src/test/java/seedu/controller/InventoryControllerTest.java
Labels: type.enhancement

#173 create default dir and file
  build.gradle
  database/books.txt
  database/users.txt
  src/main/java/seedu/dukeofbooks/DukeOfBooks.java
  src/main/java/seedu/dukeofbooks/ReadWriteData.java
  src/main/java/seedu/dukeofbooks/common/DefaultBooks.java
  tp.jar
Labels: type.enhancement

#174 feat: guide in pdf version
  docs/DeveloperGuide.md
  docs/DeveloperGuide.pdf
  docs/UserGuide.pdf
Labels: documentation
